### ISSUE TITLE
java.lang.NullPointerException at PaymentServiceImpl.fetchPublicKey(PaymentServiceImpl.java:51)

### ISSUE THREAD

**Issue by SMShark** [Adyen/AdyenCheckout-android#6]
Hello, 

I have integrated it into my project by importing both the “adyenpaysdk” and “adyenuisdk” as modules in my Android project. I’ve connected everything to my app as well - clicking on the “Buy” button sets the required properties and starts a new PaymentActivity to handle everything. Here’s the code used to start that new activity:

                        Adyen.getInstance().setPublicKey(publicKey);
                        Log.e("ADYEN", "\tpublic key set to: "+Adyen.getInstance().getPublicKey());
                        Adyen.getInstance().setToken(token);
                        Log.e("ADYEN", "\ttoken set to: "+Adyen.getInstance().getToken());
                        Adyen.getInstance().setUseTestBackend(true);
                        Log.e("ADYEN", "\ttest-backend set to: "+Adyen.getInstance().isUseTestBackend());
                        Log.e("ADYEN", "--> CheckoutRequest() part");
                        CheckoutRequest checkoutRequest = new CheckoutRequest();
                        try {
                            checkoutRequest.setBrandColor(R.color.adyen_green);
                            checkoutRequest.setBrandLogo(R.drawable.splash_logo);
                            checkoutRequest.setCheckoutAmount((float)item.getPrice());
                            checkoutRequest.setCurrency(Currency.GBP);
                            checkoutRequest.setToken(token);
                            checkoutRequest.setTestBackend(true);//default is set to false. Set it to true if you want to use Adyen's test back-end.

                            Intent intent = new PaymentActivity.PaymentActivityBuilder(checkoutRequest).build(FragmentFeed.this, getContext());
                            Log.e("ADYEN", "\t--> startActivity("+intent+")");
                            startActivity(intent);
                        } catch (CheckoutRequestException e) {
                            Log.e("ADYEN", e.getMessage(), e);
                        }

And the payment activity launches fine. But as soon as I enter the card number, expiration date and CVC - and click the “Pay” button - the following crash happens in “adyenpaysdk” part of the code, the PaymentServiceImpl to be more exact. Here’s a full stacktrace:

	D/AndroidRuntime(32503): Shutting down VM
	E/AndroidRuntime(32503): FATAL EXCEPTION: main
	E/AndroidRuntime(32503): java.lang.NullPointerException
	E/AndroidRuntime(32503): 	at adyen.com.adyenpaysdk.services.PaymentServiceImpl.fetchPublicKey(PaymentServiceImpl.java:51)
	E/AndroidRuntime(32503): 	at adyen.com.adyenpaysdk.Adyen.fetchPublicKey(Adyen.java:53)
	E/AndroidRuntime(32503): 	at adyen.com.adyenuisdk.PaymentActivity$2.onClick(PaymentActivity.java:212)
	E/AndroidRuntime(32503): 	at android.view.View.performClick(View.java:4475)
	E/AndroidRuntime(32503): 	at android.view.View$PerformClick.run(View.java:18786)
	E/AndroidRuntime(32503): 	at android.os.Handler.handleCallback(Handler.java:730)
	E/AndroidRuntime(32503): 	at android.os.Handler.dispatchMessage(Handler.java:92)
	E/AndroidRuntime(32503): 	at android.os.Looper.loop(Looper.java:176)
	E/AndroidRuntime(32503): 	at android.app.ActivityThread.main(ActivityThread.java:5419)
	E/AndroidRuntime(32503): 	at java.lang.reflect.Method.invokeNative(Native Method)
	E/AndroidRuntime(32503): 	at java.lang.reflect.Method.invoke(Method.java:525)
	E/AndroidRuntime(32503): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
	E/AndroidRuntime(32503): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
	E/AndroidRuntime(32503): 	at dalvik.system.NativeStart.main(Native Method)

I’m kinda stuck here since a similar implementation works fine in the sample project (and gives expected callbacks), but there’s not much I can do if the app fails to load my public key. Any support on this matter would be most welcome. I would be grateful if you could help me adjust this so I could get one of the two expected callbacks - checkoutAuthorizedPayment(CheckoutResponse checkoutResponse)
or
checkoutFailedWithError(String errorMessage)

**Comment by nikacotAndroid** [comment]
Hey @SMShark . 

I guess that NetworkController.getInstance() returns null in the PaymentServiceImpl class.  This happens because the context of Application of the library is null.
I guess that you have two Application classes, one in your main project and one in the Adyen SDK library. The quick solution is to leave NetworkController to extends from Application, but in you main project your application class should extands NetworkController.
So:
```
NetworkController extands Application
....
YourApplication extands NetworkController
....
```

and don't forget to add in the AndroidManifest in your main project 

```
<application
        android:name="YOUR_PACKAGE_NAME.YourApplication"
.... />
```

Cheers!

**Comment by SMShark** [comment]
Hey @nikacotAndroid - that's exactly what I did to bypass the problem :) Thanks for the help.
